spring:
  application:
    name: financeHealthAnalyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance_metrics
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

telegram:
  bot:
    name: FinanceHealthAnalyzerBoy
    token: ${BOT_TOKEN}